CLASS ztp_exercise_eml DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES if_oo_adt_classrun .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZTP_EXERCISE_EML IMPLEMENTATION.


  METHOD if_oo_adt_classrun~main.

  CONSTANTS:
   C_AGENCY_ID TYPE ZTP_TRAVEL-agency_id VALUE '1909',
   C_TRAVEL_ID TYPE ZTP_TRAVEL-travel_id VALUE '19'.

  ENDMETHOD.
ENDCLASS.
